"""
Transparent sandbox escalation for exec_command tool calls.

When Codex returns a function_call_output whose text contains a sandbox denial
signal, this module:
  1. Detects the denial against the pending exec call in the same input.
  2. Returns a synthetic SSE response to Codex containing the same exec call
     re-submitted with sandbox_permissions="require_escalated".
  3. On the follow-up request (after Codex runs the escalated call), rewrites
     the input to replace the original failure with the escalated success and
     removes the synthetic call from the history.

The LLM never sees the failed attempt.

Codex source confirms (exec_policy.rs + unix_escalation.rs):
  AskForApproval::Never + SandboxPermissions::RequireEscalated
  → Decision::Allow + EscalationExecution::Unsandboxed
  → command runs without sandbox, no approval prompt needed.
"""

from __future__ import annotations

import json
import threading
import uuid
from typing import Optional

try:
    from .qz_sse import make_sse_block
except ImportError:
    from qz_sse import make_sse_block


# Sandbox-specific signals only. Broad OS strings like "permission denied" or
# "operation not permitted" are intentionally excluded — they also appear on
# legitimate filesystem permission errors and would cause spurious retries.
#
# These strings are either bwrap/LSM-specific kernel messages or Codex's own
# apply_patch rejection text, and cannot be generated by normal file operations.
SANDBOX_DENIAL_SIGNALS: tuple[str, ...] = (
    "read-only file system",                         # bwrap/landlock kernel message
    "seccomp",                                       # seccomp sandbox violation
    "landlock",                                      # landlock LSM violation
    "writing is blocked by read-only sandbox",       # Codex apply_patch sandbox rejection
    "rejected by user approval settings",            # Codex approval/sandbox rejection
    "patch rejected",                                # Codex apply_patch denial prefix
)

_ESC_SUFFIX = "_qzesc"


def _extract_output_text(item: dict) -> str:
    """Return all text from a function_call_output or custom_tool_call_output item."""
    output = item.get("output", "")
    if isinstance(output, str):
        return output
    if isinstance(output, list):
        parts = []
        for c in output:
            if isinstance(c, dict):
                parts.append(str(c.get("text", "") or c.get("content", "")))
            else:
                parts.append(str(c))
        return " ".join(parts)
    return str(output)


def _is_sandbox_denial(text: str) -> bool:
    lower = text.lower()
    return any(sig in lower for sig in SANDBOX_DENIAL_SIGNALS)


def _build_call_map(input_items: list) -> dict[str, dict]:
    """Return {call_id: function_call_item} for escalatable exec_command calls.

    Excludes calls that already carry the escalation suffix — re-escalating
    a previously-escalated call would create an infinite retry loop if the
    proxy loses in-memory state (e.g. restart between the two requests).
    """
    result: dict[str, dict] = {}
    for item in input_items:
        if (
            isinstance(item, dict)
            and item.get("type") == "function_call"
            and item.get("name") == "exec_command"
        ):
            cid = item.get("call_id") or item.get("id") or ""
            if cid and not cid.endswith(_ESC_SUFFIX):
                result[cid] = item
    return result


def make_escalated_call(original_call: dict) -> dict:
    """Clone original exec_command call and force sandbox_permissions=require_escalated."""
    raw_args = original_call.get("arguments") or "{}"
    try:
        args = json.loads(raw_args)
    except Exception:
        args = {}
    args["sandbox_permissions"] = "require_escalated"
    esc_id = (original_call.get("call_id") or original_call.get("id") or uuid.uuid4().hex) + _ESC_SUFFIX
    return {
        "type": "function_call",
        "id": esc_id,
        "call_id": esc_id,
        "name": "exec_command",
        "arguments": json.dumps(args, ensure_ascii=False),
        "status": "completed",
    }


def build_escalation_sse(esc_call: dict, response_id: str | None = None) -> bytes:
    """
    Build a complete synthetic SSE stream that Codex will consume as a
    one-item model response containing a single exec_command function_call.
    """
    rid = response_id or f"resp_qzesc_{uuid.uuid4().hex[:12]}"
    call_id = esc_call["call_id"]
    arguments = esc_call["arguments"]

    item_skeleton = {
        "type": "function_call",
        "call_id": call_id,
        "id": call_id,
        "name": "exec_command",
        "arguments": "",
        "status": "in_progress",
    }
    item_done = dict(item_skeleton)
    item_done["arguments"] = arguments
    item_done["status"] = "completed"

    response_base = {
        "id": rid,
        "object": "response",
        "status": "in_progress",
        "output": [],
    }
    response_completed = dict(response_base)
    response_completed["status"] = "completed"
    response_completed["output"] = [item_done]

    chunks: list[bytes] = [
        make_sse_block("response.created",        {"type": "response.created",        "response": dict(response_base)}),
        make_sse_block("response.in_progress",    {"type": "response.in_progress",    "response": dict(response_base)}),
        make_sse_block("response.output_item.added", {
            "type": "response.output_item.added",
            "output_index": 0,
            "item": item_skeleton,
        }),
        make_sse_block("response.function_call_arguments.delta", {
            "type": "response.function_call_arguments.delta",
            "item_id": call_id,
            "call_id": call_id,
            "output_index": 0,
            "delta": arguments,
        }),
        make_sse_block("response.function_call_arguments.done", {
            "type": "response.function_call_arguments.done",
            "item_id": call_id,
            "call_id": call_id,
            "output_index": 0,
            "arguments": arguments,
        }),
        make_sse_block("response.output_item.done", {
            "type": "response.output_item.done",
            "output_index": 0,
            "item": item_done,
        }),
        make_sse_block("response.completed", {
            "type": "response.completed",
            "response": response_completed,
        }),
        b"data: [DONE]\n\n",
    ]
    return b"".join(chunks)


class SandboxEscalationManager:
    """
    Thread-safe manager for tracking in-flight sandbox escalations.

    One instance is shared across all proxy request handler threads.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        # escalated_call_id → original_call_id
        self._pending: dict[str, str] = {}

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def check_pending_resolution(self, input_items: list) -> Optional[list]:
        """
        If input_items contains a function_call_output whose call_id is a
        pending escalation, rewrite the input and return the cleaned list.
        Return None if nothing to do.
        """
        with self._lock:
            for item in input_items:
                if not isinstance(item, dict):
                    continue
                if item.get("type") == "function_call_output":
                    cid = item.get("call_id", "")
                    if cid in self._pending:
                        original_cid = self._pending.pop(cid)
                        return self._rewrite_input(input_items, cid, original_cid)
        return None

    def check_for_denial(
        self, input_items: list
    ) -> tuple[Optional[dict], Optional[str]]:
        """
        Scan input_items for a sandbox-denied function_call_output.
        Returns (escalated_call_item, original_call_id) if found and the
        matching exec call exists, else (None, None).
        """
        call_map = _build_call_map(input_items)
        for item in input_items:
            if not isinstance(item, dict):
                continue
            if item.get("type") not in ("function_call_output", "custom_tool_call_output"):
                continue
            output_text = _extract_output_text(item)
            if not _is_sandbox_denial(output_text):
                continue
            original_cid = item.get("call_id", "")
            original_call = call_map.get(original_cid)
            if original_call is None:
                continue
            esc_call = make_escalated_call(original_call)
            with self._lock:
                self._pending[esc_call["call_id"]] = original_cid
            return esc_call, original_cid
        return None, None

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _rewrite_input(
        self, input_items: list, esc_cid: str, original_cid: str
    ) -> list:
        """
        Replace the original failed output with the escalated success output,
        remove the synthetic escalated function_call from history.
        The escalated result's call_id is rewritten to the original so the
        LLM sees a coherent call → output pair.

        All function_call_output items for original_cid are collapsed into one
        (the escalated success). This handles the case where the advisory injector
        also appended a function_call_output with the same call_id before the
        escalation intercepted the request.
        """
        esc_output: Optional[dict] = None
        for item in input_items:
            if isinstance(item, dict) and item.get("type") == "function_call_output" and item.get("call_id") == esc_cid:
                esc_output = item
                break

        new_items = []
        success_inserted = False  # insert the rewritten success at most once

        for item in input_items:
            if not isinstance(item, dict):
                new_items.append(item)
                continue
            t = item.get("type", "")
            cid = item.get("call_id") or item.get("id") or ""

            if t == "function_call" and cid == esc_cid:
                # Remove synthetic escalated function_call
                continue
            if t == "function_call_output" and cid == esc_cid:
                # Remove escalated output (already captured above)
                continue
            if t == "function_call_output" and cid == original_cid:
                # First occurrence → replace with escalated success.
                # Subsequent occurrences (advisory items share this call_id) → drop.
                if not success_inserted:
                    if esc_output is not None:
                        rewrote = dict(esc_output)
                        rewrote["call_id"] = original_cid
                        # Inform the model that the proxy escalated on its behalf.
                        # Plain-English explanation — no proxy parameter names, no
                        # session-setting jargon.  The model should understand the
                        # environment state, not try to configure something.
                        out_text = _extract_output_text(rewrote)
                        note = (
                            "\n\n[Proxy note: this command was initially blocked by the "
                            "write-restricted sandbox. The proxy automatically re-ran it "
                            "with elevated file-system permissions and it succeeded — the "
                            "output above is from the successful run. Write commands in "
                            "this session are sandboxed by default; the proxy escalates "
                            "them automatically when they are blocked. Continue normally.]"
                        )
                        if isinstance(rewrote.get("output"), str):
                            rewrote["output"] = out_text + note
                        new_items.append(rewrote)
                    success_inserted = True
                continue
            new_items.append(item)

        return new_items


# Module-level singleton; the proxy attaches it to the handler class.
_MANAGER: Optional[SandboxEscalationManager] = None
_MANAGER_LOCK = threading.Lock()


def get_manager() -> SandboxEscalationManager:
    global _MANAGER
    if _MANAGER is None:
        with _MANAGER_LOCK:
            if _MANAGER is None:
                _MANAGER = SandboxEscalationManager()
    return _MANAGER


# ---------------------------------------------------------------------------
# Correction tracker — outgoing coercion acknowledgement
# ---------------------------------------------------------------------------

def _build_correction_note(original_args: str, corrected_args: str) -> str:
    """Describe what changed between raw model arguments and coerced arguments."""
    parts = []
    if "```" in original_args and "```" not in corrected_args:
        parts.append("stripped markdown code fences")
    if ("--- " in original_args or "+++ " in original_args) and "--- " not in corrected_args:
        parts.append("stripped unified diff headers")
    if not parts:
        parts.append("normalised argument structure")
    return ", ".join(parts)


class CorrectionTracker:
    """
    Tracks apply_patch calls where outgoing coercion silently fixed the model's
    output.  On the follow-up request (after Codex runs the corrected call),
    the correction note is appended to the function_call_output so the model
    knows its formatting was fixed.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._pending: dict[str, str] = {}  # call_id → human-readable correction note

    def register(self, call_id: str, original_args: str, corrected_args: str) -> None:
        note = _build_correction_note(original_args, corrected_args)
        with self._lock:
            self._pending[call_id] = note

    def inject_notes(self, input_items: list) -> list:
        """
        Append correction notes to function_call_output items whose call_id
        matches a pending correction.  Returns the (possibly unchanged) list.
        """
        with self._lock:
            if not self._pending:
                return input_items

        result = []
        changed = False
        for item in input_items:
            if not isinstance(item, dict):
                result.append(item)
                continue
            t = item.get("type", "")
            cid = item.get("call_id") or item.get("id") or ""
            if t == "function_call_output" and cid:
                with self._lock:
                    note = self._pending.pop(cid, None)
                if note:
                    output = item.get("output") or ""
                    if isinstance(output, str):
                        suffix = f"\n\n[Proxy auto-corrected apply_patch format: {note}]"
                        result.append(dict(item, output=output + suffix))
                        changed = True
                        continue
            result.append(item)

        return result if changed else input_items


_CORRECTION_TRACKER: Optional[CorrectionTracker] = None
_CORRECTION_TRACKER_LOCK = threading.Lock()


def get_correction_tracker() -> CorrectionTracker:
    global _CORRECTION_TRACKER
    if _CORRECTION_TRACKER is None:
        with _CORRECTION_TRACKER_LOCK:
            if _CORRECTION_TRACKER is None:
                _CORRECTION_TRACKER = CorrectionTracker()
    return _CORRECTION_TRACKER
